routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*-----------------------ОСНОВНЫЕ СТРАНИЦЫ---------------------------*/
Route::get('/', 'MainController@index')->name('index');

Route::get('/competitions', 'MainController@competitions')->name('competitions');


//РАЗЛОГИНИВАНИЕ
Route::get('logout', function (){
    Auth::logout();
    return redirect('/login');
});

//АКТИВАЦИЯ АККАУНКТА
Route::get('/activation', 'ActivateController@activate')->name('activation');



/*-----------------------АДМИНКА---------------------------*/
Route::group(['middleware' => 'guest',], function () {

    Route::get('/admin', 'AdminController@index')->name('sb-index');

    //Роуты Конкурсы
    Route::resource('competition', 'CompetitionController');

    //Роуты Новости
    Route::resource('news', 'NewsController');

    //Роуты Мероприятия
    Route::resource('event', 'EventController');

    //Роуты Услуги
    Route::resource('service', 'ServiceController');

    //Роуты Сотрудники
    Route::resource('collaborator', 'CollaboratorController');

    //Роуты Вакансии
    Route::resource('vacancy', 'VacancyController');

    //Роуты Пользователи
    Route::resource('user', 'UserController');

    //Роуты Галерея
    Route::resource('gallery', 'GalleryController');

    //Роуты История Успеха
    Route::resource('story', 'StoryController');

    //Роуты Вопрос-Ответ
    Route::resource('faq', 'FAQController');

    //Роуты Партнеры
    Route::resource('partner', 'PartnerController');


});

/*-----------------------ЛИЧНЫЙ КАБИНЕТ---------------------------*/
Route::group(['middleware' => 'user',], function () {

    Route::get('/home', 'PersonalArea@index')->name('home');

    //Роуты Заявки
    Route::resource('bid', 'BidController');

});


/*-------------------------НЕПОНЯТНАЯ ШЛЯПА-------------------------*/

Auth::routes();

app/Partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    protected $fillable = [
        'title',
        'link',
        'description',
    ];

    public function image()
    {
        return $this->morphOne('App\Image', 'imageable');
    }
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Partner;
use App\Modules\UpLoadImage;
use App\Modules\Flash;
use App\Image;

class PartnerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_panel.partner.index', ['data' => Partner::orderBy('id')->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_panel.partner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $partner = Partner::create($request->all());

        $image = new UpLoadImage($request, $partner, 'partner');
        $image->upLoad();

        Flash::create($partner);

        return redirect()->route('partner.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Partner $partner)
    {
        return view('admin_panel.partner.edit', ['object' => $partner]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Partner $partner)
    {
        if ($request->has('oldImage')) {
            Image::destroy($request->input('oldImage'));
        }

        $partner->fill($request->all())->update();

        $image = new UpLoadImage($request, $partner, 'partner');
        $image->upLoad();

        Flash::edit($partner);

        return redirect()->route('partner.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Partner $partner)
    {
        Flash::delete($partner->delete());
        return redirect()->route('partner.index');
    }
}

resources/views/admin_panel/partner/create.blade.php
@extends('admin_panel.layout')

@section('title', 'Добавить нового партнера')

@section('content')

    <h3>Добавить новый конкурс</h3>
    {!! Form::open(['route' => ['partner.store'], 'files' => true]) !!}

        <div class="form-group">
            <label for="title">Название</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>

        <div class="form-group">
            <label for="title">Ссылка</label>
            <input type="text" class="form-control" id="title" name="link">
        </div>

        <div class="form-group">
            <label for="images">Добавить логоттип</label><br>
            <input type="file" name="images[]">
        </div>

        <div class="form-group">
            <label for="summernote">Описание</label><br>
            <textarea id="summernote" name="description"></textarea>
        </div>

        <button type="submit" id="sb-update" class="btn btn-success">Добавить</button>
    {!! Form::close() !!}

@endsection

@section('script')
    <script>
        $(window).ready(function () {
            $('#summernote').summernote({
                lang: 'ru-RU',
                placeholder: 'Описание мероприятия',
                tabsize: 2,
                height: 200
            });
        });
    </script>
@endsection

resources/views/admin_panel/partner/edit.blade.php
@extends('admin_panel.layout')

@section('title', 'Редактировать информацию')

@section('content')
    <h3>{{ $object->title }}</h3>
    <form method="post" action="{{ route('partner.destroy', ['id' => $object->id]) }}">
        <input type="hidden" name="_method" value="delete" >
        @csrf
        <button type="submit" class="btn btn-danger" id="deleted">Удалить</button>
    </form>

    <div class="create-update">
        <p><b>Дата добавления:</b><br> {{ $object->created_at }}</p>
        <p><b>Дата изменения:</b><br> {{ $object->updated_at }}</p>
    </div>

    {!! Form::open(['route' => ['partner.update', 'competition' => $object->id], 'method' => 'PUT', 'files' => true, 'id' => 'sb-form']) !!}

        <div class="form-group">
            <label for="name">Название</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ $object->title }}">
        </div>

        <div class="form-group">
            {{ Form::label('oldImage', 'Изображения', ['class' => 'h5']) }}
            <span>Поставте галочку если хотите удалить файл</span>
            <br>
            <div class="images">
                <img src="/storage/{{$object->image->file}}" style="width: 250px; height: 60px;">
                <div class="delite-images">
                    <input type="checkbox" value="{{ $object->image->id }}" name="oldImage[]"> Удалить
                </div>
            </div>

        </div>

        <div class="form-group" style="width: 100%;">
            {{ Form::label('images', 'Прирепить изображение', ['class' => 'h5']) }}<br>
            <input id="image-id" type="file" name="images[]" multiple class="file" data-preview-file-type="text">
        </div>

        <div class="form-group">
            <label for="summernote">Описание конкурса</label><br>
            <textarea id="summernote" name="description">{{ $object->description }}</textarea>
        </div>

        <button type="submit" id="sb-update" class="btn btn-success">Обновить</button>
    {!! Form::close() !!}
@endsection

@section('script')
    <script>
        $('#summernote').summernote({
            lang: 'ru-RU',
            placeholder: 'Описание мероприятия',
            tabsize: 2,
            height: 200
        });

    </script>
@endsection

resources/views/admin_panel/partner/index.blade.php
@extends('admin_panel.layout')

@section('title', 'Партнеры')

@section('create')
    <a class="btn btn-success" href="{{ route('partner.create')}}">Добавить партнера</a>
@endsection

@section('content')
    <table class="table table-dark" style="margin-top: 20px;">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя</th>
            <th scope="col">Сылка</th>
            <th scope="col">Лого</th>
        </tr>
        </thead>
        <tbody>
        @foreach($data as $item)
            <tr>
                <td>{{$item->id}}</td>
                <td> <a href="{{ route('partner.edit', ['id'=> $item->id]) }}"> {{$item->title}} </a> </td>
                <td>{{$item->link}}</td>
                <td><img src="/storage/{{$item->image->file}}" style="width: 250px; height: 60px;"></td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $data->render() }}
@endsection