routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*-----------------------ОСНОВНЫЕ СТРАНИЦЫ---------------------------*/
Route::get('/', 'MainController@index')->name('index');

Route::get('/competitions', 'MainController@competitions')->name('competitions');


//РАЗЛОГИНИВАНИЕ
Route::get('logout', function (){
    Auth::logout();
    return redirect('/login');
});

//АКТИВАЦИЯ АККАУНКТА
Route::get('/activation', 'ActivateController@activate')->name('activation');



/*-----------------------АДМИНКА---------------------------*/
Route::group(['middleware' => 'guest',], function () {

    Route::get('/admin', 'AdminController@index')->name('sb-index');

    //Роуты Конкурсы
    Route::resource('competition', 'CompetitionController');

    //Роуты Новости
    Route::resource('news', 'NewsController');

    //Роуты Мероприятия
    Route::resource('event', 'EventController');

    //Роуты Услуги
    Route::resource('service', 'ServiceController');

    //Роуты Сотрудники
    Route::resource('collaborator', 'CollaboratorController');

    //Роуты Вакансии
    Route::resource('vacancy', 'VacancyController');

    //Роуты Пользователи
    Route::resource('user', 'UserController');

    //Роуты Галерея
    Route::resource('gallery', 'GalleryController');

    //Роуты История Успеха
    Route::resource('story', 'StoryController');

    //Роуты Вопрос-Ответ
    Route::resource('faq', 'FAQController');

    //Роуты Партнеры
    Route::resource('partner', 'PartnerController');


});

/*-----------------------ЛИЧНЫЙ КАБИНЕТ---------------------------*/
Route::group(['middleware' => 'user',], function () {

    Route::get('/home', 'PersonalArea@index')->name('home');

    //Роуты Заявки
    Route::resource('bid', 'BidController');

});


/*-------------------------НЕПОНЯТНАЯ ШЛЯПА-------------------------*/

Auth::routes();

app/Collaborator.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Collaborator extends Model
{
    protected $fillable = [
        'name',
        'email',
        'phone',
        'position'
    ];

    public function image()
    {
        return $this->morphOne('App\Image', 'imageable');
    }
}

app/Http/Controllers/CollaboratorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Collaborator;
use App\Modules\UpLoadImage;
use App\Modules\Flash;
use App\Image;

class CollaboratorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_panel.collaborator.index', ['data' => Collaborator::orderBy('id')->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_panel.collaborator.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $collab = Collaborator::create($request->all());

        $image = new UpLoadImage($request, $collab, 'collaboration');
        $image->upLoad();

        Flash::create($collab);

        return redirect()->route('collaborator.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Collaborator $collaborator)
    {
        return view('admin_panel.collaborator.edit', ['object' => $collaborator]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Collaborator $collaborator)
    {
        if ($request->has('oldImage')) {
            Image::destroy($request->input('oldImage'));
        }

        $collaborator->fill($request->all())->update();

        $image = new UpLoadImage($request, $collaborator, 'collaborator');
        $image->upLoad();

        Flash::edit($collaborator);

        return redirect()->route('collaborator.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Collaborator $collaborator)
    {
        Flash::delete($collaborator->delete());
        return redirect()->route('competition.index');
    }
}

resources/views/admin_panel/collaborator/create.blade.php
@extends('admin_panel.layout')

@section('title', 'Добавить нового сотрудника')

@section('content')

    <h3>Добавить новый конкурс</h3>
    {!! Form::open(['route' => ['collaborator.store'], 'files' => true]) !!}

    <div class="form-group">
        <label for="title">ФИО</label>
        <input type="text" class="form-control" id="name" name="name">
    </div>

    <div class="form-group">
        <label for="title">Должность</label>
        <input type="text" class="form-control" id="position" name="position">
    </div>

    <div class="form-group">
        <label for="title">E-Mail</label>
        <input type="email" class="form-control" id="email" name="email">
    </div>

    <div class="form-group">
        <label for="title">Телефон</label>
        <input type="number" class="form-control" id="phone" name="phone">
    </div>

    <div class="form-group">
        <label for="images">Прикрепить фото</label><br>
        <input type="file" name="images[]">
    </div>

    <button type="submit" id="sb-update" class="btn btn-success">Добавить</button>
    {!! Form::close() !!}

@endsection

@section('script')
    <script>
        $(window).ready(function () {
            $('#summernote').summernote({
                lang: 'ru-RU',
                placeholder: 'Описание мероприятия',
                tabsize: 2,
                height: 200
            });

        });
    </script>
@endsection

resources/views/admin_panel/collaborator/edit.blade.php
@extends('admin_panel.layout')

@section('title', 'Редактировать информацию сотрудника')

@section('content')
    <h3>{{ $object->name }}</h3>
    <form method="post" action="{{ route('collaborator.destroy', ['id' => $object->id]) }}">
        <input type="hidden" name="_method" value="delete" >
        @csrf
        <button type="submit" class="btn btn-danger" id="deleted">Удалить</button>
    </form>

    <div class="create-update">
        <p><b>Дата добавления:</b><br> {{ $object->created_at }}</p>
        <p><b>Дата изменения:</b><br> {{ $object->updated_at }}</p>
    </div>

    {!! Form::open(['route' => ['competition.update', 'competition' => $object->id], 'method' => 'PUT', 'files' => true, 'id' => 'sb-form']) !!}

    <div class="form-group">
        <label for="name">ФИО</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ $object->name }}">
    </div>

    <div class="form-group">
        <label for="name">Должность</label>
        <input type="text" class="form-control" id="position" name="position" value="{{ $object->position }}">
    </div>

    <div class="form-group">
        <label for="name">E-Mail</label>
        <input type="email" class="form-control" id="email" name="email" value="{{ $object->email }}">
    </div>

    <div class="form-group">
        <div class="images">
            <img src="/storage/{{$object->image}}" width="100" height="100">
            <div class="delite-images">
                <input type="checkbox" value="{{ $object->image }}" name="oldImage[]"> Удалить
            </div>
        </div>
    </div>

    <div class="form-group" style="width: 100%;">
        {{ Form::label('images', 'Прирепить изображение', ['class' => 'h5']) }}<br>
        <input id="image-id" type="file" name="images[]" multiple class="file" data-preview-file-type="text">
    </div>


    <button type="submit" id="sb-update" class="btn btn-success">Обновить</button>
    {!! Form::close() !!}
@endsection

@section('script')

@endsection

resources/views/admin_panel/collaborator/index.blade.php
@extends('admin_panel.layout')

@section('title', 'Сотрудники')

@section('create')
    <a class="btn btn-success" href="{{ route('collaborator.create')}}">Добавить сотрудника</a>
@endsection

@section('content')
    <table class="table table-dark" style="margin-top: 20px;">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ФИО</th>
            <th scope="col">Должность</th>
            <th scope="col">E-mail</th>
            <th scope="col">Телефон</th>
        </tr>
        </thead>
        <tbody>
        @foreach($data as $item)
            <tr>
                <td>{{$item->id}}</td>
                <td> <a href="{{ route('collaborator.edit', ['id'=> $item->id]) }}"> {{$item->name}} </a> </td>
                <td>{{$item->position}}</td>
                <td>{{$item->email}}</td>
                <td>{{$item->phone}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $data->render() }}
@endsection