routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*-----------------------ОСНОВНЫЕ СТРАНИЦЫ---------------------------*/
Route::get('/', 'MainController@index')->name('index');

Route::get('/competitions', 'MainController@competitions')->name('competitions');


//РАЗЛОГИНИВАНИЕ
Route::get('logout', function (){
    Auth::logout();
    return redirect('/login');
});

//АКТИВАЦИЯ АККАУНКТА
Route::get('/activation', 'ActivateController@activate')->name('activation');



/*-----------------------АДМИНКА---------------------------*/
Route::group(['middleware' => 'guest',], function () {

    Route::get('/admin', 'AdminController@index')->name('sb-index');

    //Роуты Конкурсы
    Route::resource('competition', 'CompetitionController');

    //Роуты Новости
    Route::resource('news', 'NewsController');

    //Роуты Мероприятия
    Route::resource('event', 'EventController');

    //Роуты Услуги
    Route::resource('service', 'ServiceController');

    //Роуты Сотрудники
    Route::resource('collaborator', 'CollaboratorController');

    //Роуты Вакансии
    Route::resource('vacancy', 'VacancyController');

    //Роуты Пользователи
    Route::resource('user', 'UserController');

    //Роуты Галерея
    Route::resource('gallery', 'GalleryController');

    //Роуты История Успеха
    Route::resource('story', 'StoryController');

    //Роуты Вопрос-Ответ
    Route::resource('faq', 'FAQController');

    //Роуты Партнеры
    Route::resource('partner', 'PartnerController');


});

/*-----------------------ЛИЧНЫЙ КАБИНЕТ---------------------------*/
Route::group(['middleware' => 'user',], function () {

    Route::get('/home', 'PersonalArea@index')->name('home');

    //Роуты Заявки
    Route::resource('bid', 'BidController');

});


/*-------------------------НЕПОНЯТНАЯ ШЛЯПА-------------------------*/

Auth::routes();

app/Http/Controllers/PersonalArea.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PersonalArea extends Controller
{

    public function index()
    {
        if (Auth::user()->token == 'active') {
            return view('personal_area.index');
        }
        else {
            return view('personal_area.active');
        }
    }

}

resources/views/personal_area/components/navbar.blade.php
<div class="menu">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{{ route('bid.create') }}">Подать заявку на конкурс</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Вебинары</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Стать оставщиком</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Получить услугу</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Задать вопрос</a>
        </li>
    </ul>
</div>