routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*-----------------------ОСНОВНЫЕ СТРАНИЦЫ---------------------------*/
Route::get('/', 'MainController@index')->name('index');

Route::get('/competitions', 'MainController@competitions')->name('competitions');


//РАЗЛОГИНИВАНИЕ
Route::get('logout', function (){
    Auth::logout();
    return redirect('/login');
});

//АКТИВАЦИЯ АККАУНКТА
Route::get('/activation', 'ActivateController@activate')->name('activation');



/*-----------------------АДМИНКА---------------------------*/
Route::group(['middleware' => 'guest',], function () {

    Route::get('/admin', 'AdminController@index')->name('sb-index');

    //Роуты Конкурсы
    Route::resource('competition', 'CompetitionController');

    //Роуты Новости
    Route::resource('news', 'NewsController');

    //Роуты Мероприятия
    Route::resource('event', 'EventController');

    //Роуты Услуги
    Route::resource('service', 'ServiceController');

    //Роуты Сотрудники
    Route::resource('collaborator', 'CollaboratorController');

    //Роуты Вакансии
    Route::resource('vacancy', 'VacancyController');

    //Роуты Пользователи
    Route::resource('user', 'UserController');

    //Роуты Галерея
    Route::resource('gallery', 'GalleryController');

    //Роуты История Успеха
    Route::resource('story', 'StoryController');

    //Роуты Вопрос-Ответ
    Route::resource('faq', 'FAQController');

    //Роуты Партнеры
    Route::resource('partner', 'PartnerController');


});

/*-----------------------ЛИЧНЫЙ КАБИНЕТ---------------------------*/
Route::group(['middleware' => 'user',], function () {

    Route::get('/home', 'PersonalArea@index')->name('home');

    //Роуты Заявки
    Route::resource('bid', 'BidController');

});


/*-------------------------НЕПОНЯТНАЯ ШЛЯПА-------------------------*/

Auth::routes();

app/Competition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Competition extends Model
{
    protected $fillable = [
        'title',
        'date_start',
        'date_end',
        'description',
    ];

    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }

    public function image()
    {
        return $this->morphMany('App\Image', 'imageable');
    }

    public function bid()
    {
        return $this->morphMany('App\Bid', 'bidable');
    }
}

app/Http/Controllers/CompetitionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Competition;
use App\Modules\UpLoadDocument;
use App\Modules\UpLoadImage;
use App\Modules\Flash;
use App\Document;
use App\Image;

class CompetitionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_panel.competitions.index', ['data' => Competition::orderBy('id')->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_panel.competitions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $comp = Competition::create($request->all());

        $doc = new UpLoadDocument($request, $comp, 'competition');
        $doc->upLoad();

        $image = new UpLoadImage($request, $comp, 'competition');
        $image->upLoad();
        Flash::create($comp);

        return redirect()->route('competition.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Competition $competition)
    {
        return view('admin_panel.competitions.edit', ['object' => $competition]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Competition $competition)
    {
        if ($request->has('oldDocument')) {
            Document::destroy($request->input('oldDocument'));
        }

        if ($request->has('oldImage')) {
            Image::destroy($request->input('oldImage'));
        }

        $competition->fill($request->all())->update();

        $doc = new UpLoadDocument($request, $competition, 'competition');
        $doc->upLoad();

        $image = new UpLoadImage($request, $competition, 'competition');
        $image->upLoad();

        Flash::edit($competition);

        return redirect()->route('competition.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Competition $competition)
    {
        Flash::delete($competition->delete());
        return redirect()->route('competition.index');
    }
}

resources/views/admin_panel/competitions/create.blade.php
@extends('admin_panel.layout')

@section('title', 'Создать новый конкурс')

@section('content')

    <h3>Добавить новый конкурс</h3>
    {!! Form::open(['route' => ['competition.store'], 'files' => true]) !!}

        <div class="form-group">
            <label for="title">Название</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>

        <label>Время проведения конкурса</label><br>
        <div class="form-group" style="width: 20%;float: left; display: inline-block; margin-right: 20px;">
            <label for="date_start">Дата начала</label>
            <input type="datetime-local" class="form-control" id="date_start" name="date_start">
        </div>
        <div class="form-group" style="width: 20%; display: inline-block">
            <label for="date_end">Дата окончания</label>
            <input type="datetime-local" class="form-control" id="date_end" name="date_end">
        </div>

        <div class="form-group">
            <label for="summernote">Описание конкурса</label><br>
            <textarea id="summernote" name="description"></textarea>
        </div>

        <div class="form-group">
            <label for="images">Прикрепить фото</label><br>
            <input type="file" name="images[]" multiple>
        </div>

        <div class="form-group">
            <label for="documents">Прикрепить документы</label><br>
            <input type="file" name="documents[]" multiple>
        </div>

        <button type="submit" id="sb-update" class="btn btn-success">Добавить</button>
    {!! Form::close() !!}

@endsection

@section('script')
    <script>
        $(window).ready(function () {
            $('#summernote').summernote({
                lang: 'ru-RU',
                placeholder: 'Описание мероприятия',
                tabsize: 2,
                height: 200
            });

        });
    </script>
@endsection

resources/views/admin_panel/competitions/edit.blade.php
@extends('admin_panel.layout')

@section('title', 'Редактировать конкурс')

@section('content')
    <h3>{{ $object->title }}</h3>
    <form method="post" action="{{ route('competition.destroy', ['id' => $object->id]) }}">
        <input type="hidden" name="_method" value="delete" >
        @csrf
        <button type="submit" class="btn btn-danger" id="deleted">Удалить</button>
    </form>

    <div class="create-update">
        <p><b>Дата добавления:</b><br> {{ $object->created_at }}</p>
        <p><b>Дата изменения:</b><br> {{ $object->updated_at }}</p>
    </div>

    {!! Form::open(['route' => ['competition.update', 'competition' => $object->id], 'method' => 'PUT', 'files' => true, 'id' => 'sb-form']) !!}

        <div class="form-group">
            <label for="name">Название</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ $object->title }}">
        </div>

        <div class="form-group">
            {{ Form::label('oldImage', 'Изображения', ['class' => 'h5']) }}
            <span>Поставте галочку если хотите удалить файл</span>
            <br>

            @foreach($object->image as $image)
                <div class="images">
                    <img src="/storage/{{$image->file}}" width="100" height="100">
                    <div class="delite-images">
                        <input type="checkbox" value="{{ $image->id }}" name="oldImage[]"> Удалить
                    </div>
                </div>
            @endforeach
        </div>

        <div class="form-group" style="width: 100%;">
            {{ Form::label('images', 'Прирепить изображение', ['class' => 'h5']) }}<br>
            <input id="image-id" type="file" name="images[]" multiple class="file" data-preview-file-type="text">
        </div>

        <label>Время проведения конкурса</label><br>
        <div class="form-group" style="width: 25%;float: left; display: inline-block; margin-right: 20px;">
            <label for="date_start">Дата начала</label>
            <input type="datetime-local" class="form-control" id="date_start" name="date_start" value="{{ date('Y-m-d',strtotime($object->date_start)) }}T{{ date('H:i',strtotime($object->date_start)) }}">
        </div>
        <div class="form-group" style="width: 25%; display: inline-block">
            <label for="date_end">Дата окончания</label>
            <input type="datetime-local" class="form-control" id="date_end" name="date_end" value="{{ date('Y-m-d',strtotime($object->date_end)) }}T{{ date('H:i',strtotime($object->date_end)) }}">
        </div>

        <div class="form-group">
            <label for="summernote">Описание конкурса</label><br>
            <textarea id="summernote" name="description">{{ $object->description }}</textarea>
        </div>

        <div class="form-group">
            {{ Form::label('oldDocument', 'Прикрепленные документы', ['class' => 'h5']) }}
            <span>Поставте галочку если хотите удалить файл</span>
            <br>

            @foreach( $object->document as $document)
                <div class="documents">
                    <input type="checkbox" value="{{ $document->id }}" name="oldDocument[]">
                    <a href="/storage/{{ $document->file }}" ><span>{{ $document->title }}</span></a>
                </div>
            @endforeach
        </div>

        <div class="form-group">
            {{ Form::label('documents', 'Документы', ['class' => 'h5']) }}
            <input id="input-id" type="file" name="documents[]" multiple class="file">
        </div>


        <button type="submit" id="sb-update" class="btn btn-success">Обновить</button>
    {!! Form::close() !!}
@endsection

@section('script')
    <script>
        $('#summernote').summernote({
            lang: 'ru-RU',
            placeholder: 'Описание мероприятия',
            tabsize: 2,
            height: 200
        });

    </script>
@endsection

resources/views/admin_panel/competitions/index.blade.php
@extends('admin_panel.layout')

@section('title', 'Конкурсы')

@section('create')
    <a class="btn btn-success" href="{{ route('competition.create')}}">Добавить конкурс</a>
@endsection

@section('content')
    <table class="table table-dark" style="margin-top: 20px;">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Дата начала</th>
            <th scope="col">Дата окончания</th>
            <th scope="col">Статус</th>
        </tr>
        </thead>
        <tbody>
        @foreach($data as $item)
            <tr>
                <td>{{$item->id}}</td>
                <td> <a href="{{ route('competition.edit', ['id'=> $item->id]) }}"> {{$item->title}} </a> </td>
                <td>{{$item->date_start}}</td>
                <td>{{$item->date_end}}</td>
                @if( date('U') < date('U', strtotime($item->date_end)) )
                <td>Идет</td>
                @else
                <td>Окончен</td>
                @endif

            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $data->render() }}
@endsection